name: Deploy to Grad server

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]


jobs:
  test_job:
    name: Run application tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: check the files
        run: |
          echo $GITHUB_SHA
          docker build -t shehuawwal/gradtrainee:$GITHUB_SHA .

          docker images
